name: "Build Debian packages"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: A build on different Debian distributions
    strategy:
      matrix:
        codename: ['buster', 'bullseye']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Debian package action test
      uses: schacht-certat/debian-build@debian-packaging
      with:
        codename: ${{ matrix.codename }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: debian-package-${{ matrix.codename }}-${{ github.sha }}
        path: '~/artifacts'
        retention-days: 5
